### ISSUE TITLE
Redirect http://wpt.fyi/ to https://wpt.fyi/ and use HSTS

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-collection#128]
See https://github.com/whatwg/misc-server/blob/master/debian/marquee/nginx/conf/whatwg-headers.conf for an example header.

**Comment by jeffcarp** [comment]
The redirect can be done in App Engine by using [`secure: always`](https://cloud.google.com/appengine/docs/standard/python/config/appref#handlers_secure) in `app.yaml`.

Sending HSTS headers will need to be done both in `app.yaml` for static files and in our Go app for dynamic routes. We should also submit wpt.fyi to https://hstspreload.org/.

**Comment by jeffcarp** [comment]
Just realized this will break domains not yet configured with TLS. Here are all the domains currently pointing at the dashboard and whether they have a cert:

domain | certificate?
---|---
results.web-platform-tests.org | no
www.results.web-platform-tests.org | no
wpt.fyi | yes
www.wpt.fyi | no
wptdashboard.appspot.com | yes

**Comment by jeffcarp** [comment]
Since results.web-platform-tests.org is pointed at the dashboard, I think I can generate a Let's Encrypt cert for it. However we'd need to update it every 90 days, which is kind of a pain.

**Comment by bobholt** [comment]
We use [certbot](https://certbot.eff.org/) in wpt-pullresults to make renewing the letsencrypt cert completely hands-off. We set it up with ansible, but here are the steps to go through: https://github.com/w3c/wpt-pullresults/blob/master/ansible/roles/nginx/tasks/certbot.yml

**Comment by jeffcarp** [comment]
Ahh I'm an idiot, I just realized we can enable managed TLS in App Engine for all the above domains. I started the process and once those certificates are live I'll add a line to `app.yaml` to redirect insecure traffic. I think we'll need to do HSTS in the actual app, I don't think we can add it as a config.

**Comment by jeffcarp** [comment]
Ok! We're now redirecting insecure traffic. Try: http://wpt.fyi/

**Comment by lukebjerring** [comment]
_"You cannot use Strict-Transport-Security headers unless your domain is whitelisted. To place your domain in the whitelist, contact appengine-security-headers@google.com."_
https://cloud.google.com/appengine/docs/flexible/nodejs/securing-custom-domains-with-ssl#using_strict-transport-security_headers_in_a_custom_domain

**Comment by jeffcarp** [comment]
Thanks, just sent an email to that address.

**Comment by lukebjerring** [comment]
Did you hear back about this @jeffcarp ?

**Comment by jeffcarp** [comment]
No response yet :/

**Comment by PicardParis** [comment]
**Update**
As of 2018, custom domains don't need to be whitelisted. In other words, HSTS headers are not stripped out anymore.

**Comment by foolip** [comment]
Excellent, thank you @PicardParis!

**Comment by foolip** [comment]
@lukebjerring do you know why this issue wasn't migrated? I'm going to add the project:wpt.fyi to a few other issues and then maybe the open ones (including this) can be moved?

**Comment by foolip** [comment]
Closing in favor of https://github.com/web-platform-tests/wpt.fyi/issues/58
