### ISSUE TITLE
infrastructure/assumptions/ahem.html is failing in Safari

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-collection#218]
https://wpt.fyi/infrastructure/assumptions/ahem.html

Failing this test could mean that lots of other tests are also failing, which is very bad.

@mattl, can you look into why these are failing? If they're problem in Edge or Safari, let's track those bugs here until it's fixed.

Reported by @fremycompany.

**Comment by mattl** [comment]
I'll take a look shortly.

**Comment by foolip** [comment]
@mattl I've added urgent and roadmap labels to this repo so that I could add the roadmap one.

**Comment by mattl** [comment]
Sounds good.

**Comment by rwaldron** [comment]
@foolip with the following command: 

```
$ ./wpt run chrome infrastructure/assumptions/ahem.html
```

I'm seeing Chrome fail: 

```
Summary
=======

Ran 1 tests
Expected results: 0
Unexpected results: 1 (FAIL: 1)

Unexpected Results
==================

FAIL /infrastructure/assumptions/ahem.html
```

And I captured this: 

![](https://i.gyazo.com/b6a376ec510f89275746c976d60c6eb3.png)

I went to the history and the path to `fonts/Ahem.ttf` was changed here: https://github.com/w3c/web-platform-tests/blob/master/infrastructure/assumptions/ahem.html; when I changed it from `../../fonts/Ahem.ttf` to `./fonts/Ahem.ttf`, the test passes: 


```
Summary
=======

Ran 1 tests
Expected results: 1
Unexpected results: 0

OK
```

And now ahem-ref.html looks like this: 

![](https://i.gyazo.com/362bd16d1d8c44773365106e8f24ed36.png)

I'm going to open a PR on web-platform-tests, with a ref back to this comment.

**Comment by rwaldron** [comment]
lol @ me... Ignore all of that—somehow this change allows the test to pass, but it's also _not actually loading the font anymore_

**Comment by rwaldron** [comment]
This did lead me to write and open https://github.com/w3c/web-platform-tests/pull/8396

**Comment by csnardi** [comment]
It looks like this is because we don't install Ahem on Sauce instances -- only on the local machine that then runs Sauce Connect. To fix this would likely involve adding installing Ahem into the prerun scripts -- I played around with this for a little bit but I couldn't get it to work.

This also means that all Sauce builds (including CI) do not have Ahem properly installed.

**Comment by foolip** [comment]
Thanks for looking into this @csnardi! Do you think it's at all likely that this could be made to work with Sauce, or would we have to run on machines with the fonts installed?

We care about the difference between system fonts and web fonts here, and I wonder if web developers would ever face this same problem. @kereliuk, could it make sense to have WebDriver APIs to install system fonts? It's not a given that such an API could even be made to work on all OSes, but maybe?

**Comment by csnardi** [comment]
Theoretically, this shouldn't require a whole lot of work to fix with Sauce. There's a [tutorial for this for Linux](https://support.saucelabs.com/hc/en-us/articles/225097087-Installing-Fonts-on-Sauce-Labs-Virtual-Machines-to-Render-Chinese-and-Japanese-Characters), and doing a similar thing with our prerun scripts should just work. However, I didn't have a lot of luck doing that; that's likely more due to my lack of experience with Sauce rather than it not being possible though.

**Comment by kereliuk** [comment]
I'm not sure how fonts are installed on in Chromium, or how they're installed in other browsers. I am also skeptic about how hard it would be to make such a command cross-platform :/
If it is somewhat easy we could make this an extension command in ChromeDriver.

**Comment by gsnedders** [comment]
This should probably be fixed upstream in wptrunner in the Sauce support there.

@rachelandrew and @gregwhitworth have apparently run into this trying to look at the css-multicol tests.

**Comment by jugglinmike** [comment]
I agree that the fix here belongs in the WPT CLI. [This problem is also being discussed in the WPT repository](https://github.com/w3c/web-platform-tests/issues/9105), though that discussion is driving towards a much larger patch for a longer-term solution.

I'm making it a priority to implement the Sauce Labs-specific solution for now.

**Comment by foolip** [comment]
> I'm making it a priority to implement the Sauce Labs-specific solution for now.

Would that go into the WPT CLI, where you think it belong?

**Comment by jugglinmike** [comment]
Yes. The WPT CLI is already using Sauce Labs' "Pre-Run Executables" feature to [disable Edge's popups blocker](https://github.com/w3c/web-platform-tests/blob/7bbb8d0cc0cb5adad07deb1c2aa76a047f8921b7/tools/wptrunner/wptrunner/browsers/sauce_setup/edge-prerun.bat) and to [disable Safari's popup blocker](https://github.com/w3c/web-platform-tests/blob/7bbb8d0cc0cb5adad07deb1c2aa76a047f8921b7/tools/wptrunner/wptrunner/browsers/sauce_setup/safari-prerun.sh). The fix will probably be contained within those two files.

Though this begs the question: [now that Sauce Labs is no longer used to validate pull requests for WPT](https://github.com/w3c/web-platform-tests/pull/9954), will the WPT CLI continue to support integration with Sauce Labs?

@jgraham Can you speak to this at all?

**Comment by foolip** [comment]
Unless we remove it it'll stay around, but when it breaks wpt.fyi will probably be the first to notice.

**Comment by jugglinmike** [comment]
I began work on this last week after self-assigning the issue. Interestingly, the Windows half was relatively painless, and it's the macOS half which is causing me trouble. I've been talking with Sauce Labs support to ensure the VM is configured as we expect (it is), so I've started debugging with a MacBook Pro locally. I'll report here when I know more!

**Comment by jugglinmike** [comment]
[We landed a fix for Edge yesterday evening](https://github.com/w3c/web-platform-tests/pull/10499). At that time, [a patch was also merged to address the problem in Safari](https://github.com/w3c/web-platform-tests/pull/10491), but that has not been reported to consistently solve the problem, so this issue should remain open for the time being

**Comment by jugglinmike** [comment]
Validating the fix for Edge took longer than expected due to [last week's kerfuffle](https://github.com/web-platform-tests/results-collection/issues/545). With that resolved, we've successfully collected results using this solution--the proof is visible on https://wpt.fyi today:

![screenshot from 2018-04-30 17-59-41](https://user-images.githubusercontent.com/677252/39452738-57956f9e-4ca1-11e8-98c8-64ddab4b29f3.png)

Unfortunately, the fix for Safari still eludes us. Another contributor merged a patch, but it was never expected to solve the problem. We still don't understand why, though. I have a support ticket open with Sauce Labs; it's currently waiting on me to manually test on a local device.

**Comment by gsnedders** [comment]
@jugglinmike 

So fonts on macOS have this thing called "auto-activation". We could try various things with `atsutil` (see its manpage), potentially:

 * Ensuring autoactivation is enabled: `atsutil autoactivation -e ~/Library/Fonts`
 * Deleting the database and restarting fontd: `atsutil databases -removeUser && atsutil server -shutdown` (there's some warning about restarting it but…)

**Comment by jugglinmike** [comment]
That's surprising. Through my limited local testing, macOS has recognized Ahem following the introduction of the file. In other words (and unlike in Windows) no additional configuration has been needed.

Note that the pre-run script does not run with system administrator-level permissions. If those are required to execute the commands you've mentioned, then we may need to file a feature request to Sauce Labs.

**Comment by gsnedders** [comment]
@jugglinmike Yeah, it *should* work, but I presume there's some bug somewhere. None of the commands I mentioned should need root, though.

**Comment by foolip** [comment]
The Edge fix worked, now it's just failing in Safari. Progress!

**Comment by gsnedders** [comment]
@jugglinmike I assume you've tried it, but: create the directory, autoactivate it, then install the font?

**Comment by foolip** [comment]
I may have run into this again in https://github.com/foolip/wpt/pull/5/checks?check_run_id=22723523 where I'm trying to run Safari on Azure.

**Comment by jgraham** [comment]
The related bug for Gecko is https://bugzilla.mozilla.org/show_bug.cgi?id=1425698

It seems like font availability is pretty deeply tied to the way the user session is created. Do we have enough access on Azure to install the font globally rather than as a user font?

**Comment by foolip** [comment]
> Do we have enough access on Azure to install the font globally rather than as a user font?

Yeah, just putting it in /Library/Fonts worked. However, I'm not certain that's robust, and it's possible there's just a bug with `--install-fonts` that I should fix. This is solvable in any event.

**Comment by jugglinmike** [comment]
We resolved this by collecting from Safari running on a locally-manage Mac Mini (see gh-112 for Safari Technology Preview and gh-613 for the "stable" release of the browser). This is demonstrated by the latest results published to wpt.fyi:

- Safari Technology Preview: https://wpt.fyi/results/infrastructure/assumptions/ahem.html?sha=6856483bcc&label=experimental
- Safari "stable": https://wpt.fyi/results/infrastructure/assumptions/ahem.html?sha=6856483bcc&label=stable
