### ISSUE TITLE
Expose spec links for a test if they become available

### ISSUE THREAD

**Issue by jeffcarp** [web-platform-tests/results-collection#29]
Via https://crbug.com/738440

**Comment by gsnedders** [comment]
See https://github.com/w3c/web-platform-tests/issues/6507

**Comment by jgraham** [comment]
I am super-skeptical about prioritising this. Historically we haven't managed to keep spec links maintained well and intentionally tried to encode that information into the file system instead. So I would much prefer we start by making fs navigation easier before we look at link rel=help or anything similar. That would solve all the issues in the upstream bug report afaict.

**Comment by jeffcarp** [comment]
#45 adds arbitrary fs navigation, which should help on that front. I'll rename this issue to reflect the hypothetical path forward.

**Comment by foolip** [comment]
Moved to https://github.com/web-platform-tests/wpt.fyi/issues/65.
