### ISSUE TITLE
Pass/total numbers inflated by "Test file" for testharness.js tests (harness status)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-collection#427]
https://wpt.fyi/gyroscope is a directory where currently all tests except https://wpt.fyi/gyroscope/Gyroscope_insecure_context.html are actually failing, but the overall pass rates listed in https://wpt.fyi/ are 10/50.

This is because "Test file" counts as passing if there aren't any harness errors, for testharness.js tests. For test suites that are split into many files, this makes it harder to spot the "not supported at all" cases, and it would also inflate the 4/4 counts for https://github.com/w3c/wptdashboard/issues/83. Example:
https://metrics5-dot-wptdashboard.appspot.com/metrics/gyroscope/Gyroscope-disabled-by-feature-policy.https.html

@mdittmer @lukebjerring FYI ^

Since "Test file" is the main and only result for reftests the solution would not be to just omit this line. And knowing about harness errors is useful, so omitting it for just testharness.js tests is also not a complete solution.

**Comment by foolip** [comment]
I think this might work:
* Call it "Harness error" instead of "Test file" for testharness.js tests
* Don't count that in any summary numbers
* Include harness errors in the upcoming "anomalies" view.

**Comment by rwaldron** [comment]
This is being addressed in a redesign (which we've scheduled a presentation for Wed the 14th)

**Comment by foolip** [comment]
Moved to https://github.com/web-platform-tests/wpt.fyi/issues/62.
