### ISSUE TITLE
Mirror all results to BigQuery

### ISSUE THREAD

**Issue by jeffcarp** [web-platform-tests/results-collection#43]
As discussed in the [design doc](https://bit.ly/wptdashboard-design-doc), to enable people to write SQL to query results in more complex ways, we should mirror all test results to BigQuery.

Note: initially this issue stated that the mirroring would happen as part of the test run, but it doesn't necessarily need to be coupled together so closely. We could create a separate job responsible for uploading any new results to BQ.

**Comment by jeffcarp** [comment]
cc @mdittmer

**Comment by foolip** [comment]
Closing this. This would be an issue for https://github.com/web-platform-tests/wpt.fyi/issues/55, but I don't think we have a need for it right now. https://github.com/web-platform-tests/wpt.fyi/issues/53 tracks documenting where the results can be found.
