### ISSUE TITLE
Currently displaying duplicate results

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/results-collection#470]
As of 10:00 EST on 2018-02-16, https://wpt.fyi is displaying duplicate resultsfor each browser under test:

![screenshot from 2018-02-16 12-43-33](https://user-images.githubusercontent.com/677252/36321298-5171ee08-1317-11e8-91ac-c6c96a82fa8d.png)

We are investigating the cause of this issue and will report back here as we lean more.

**Comment by jugglinmike** [comment]
**Background** To explain the cause of this issue, I have to describe some implementation details of the web server code--bear with me!

Information about available browsers is defined in [a JSON-formatted file](https://github.com/w3c/wptdashboard/blob/11d55825a6f8be0f167e84bfd30d29f9a6702272/webapp/browsers.json).  The server does not load this data at initialization time. Instead, it defers loading until responding to [the first request that requires it](https://github.com/w3c/wptdashboard/blob/11d55825a6f8be0f167e84bfd30d29f9a6702272/webapp/params.go#L71).  That data is persisted in-memory, and [the server is expected to respond to all subsequent requests by referencing that data (instead of loading from disk again)](https://github.com/w3c/wptdashboard/blob/11d55825a6f8be0f167e84bfd30d29f9a6702272/webapp/util.go#L39-L48).\*

**Incident Report** This morning at about 9:30 AM EST, https://wpt.fyi received a high volume HTTP requests. The server crashed while attempting to handle this load, and the Google Cloud Platform subsequently created a new instance to replace it.

The first two requests for browser information were received within 1 millisecond of each other\*\*. The proximity of these requests coupled with the parallel execution of the GoLang processing model caused the logic for loading browser data to execute twice, producing two entries for each available browser.

We have verified this behavior in local development instance\*\*\*:

![screenshot from 2018-02-16 17-20-25](https://user-images.githubusercontent.com/677252/36336032-59de2166-1352-11e8-8de6-e96ef9e37441.png)

**Next Steps** We've corrected the immediate problem of invalid application state by re-starting the server, so https://wpt.fyi no longer displays duplicate browser results.

[We've submitted a patch to remove the race condition by loading browser data at application initialization time.](https://github.com/w3c/wptdashboard/pull/471) With this applied, no combination of requests will influence the in-memory list of available browsers.

Moving forward, we'd like to understand the nature of the requests which caused the server crash and subsequently forced the new instance into an invalid state.

\* The GoLang variable `browserNamesAlphabetical` [is declared once](https://github.com/w3c/wptdashboard/blob/3d734d2a3606300f9638c17b8b8caff5a43db07d/webapp/util.go#L19) and [extended with each invocation of `loadBrowserNames`](https://github.com/w3c/wptdashboard/blob/3d734d2a3606300f9638c17b8b8caff5a43db07d/webapp/util.go#L62-L77)  
\*\* GET requests were made to `/api/runs?sha=latest` received at 16 09:08:55.936 EST and 16 09:08:55.937 EST ([logs available here](https://console.cloud.google.com/logs/viewer?project=wptdashboard&authuser=0&resource=gae_app%2Fmodule_id%2Fdefault%2Fversion_id%2F20180112t171813&minLogLevel=0&expandAll=false&logName=projects%2Fwptdashboard%2Flogs%2Fappengine.googleapis.com%252Frequest_log&timestamp=2018-02-16T14:09:23.704112000Z&interval=JUMP_TO_TIME&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.zone%3D%22us14%22%0Aresource.labels.project_id%3D%22wptdashboard%22%0Aresource.labels.version_id%3D%2220180112t171813%22%0Aresource.labels.module_id%3D%22default%22))  
\*\*\* We reproduced the failure case by issuing two HTTP requests in rapid succession. Because this issue stems from a race condition in sub-millisecond processing, it was necessary to [modify the program code by inserting an artificial delay](https://github.com/w3c/wptdashboard/compare/master...bocoup:force-race).

**Comment by rwaldron** [comment]
Thanks for documenting this!!

**Comment by foolip** [comment]
This was fixed.

**Comment by lukebjerring** [comment]
@jugglinmike  -  logically, it feels like the issue can't happen with the patch. Did it reoccur because the patch is not actually yet deployed to prod?

**Comment by jugglinmike** [comment]
That would be my guess, though we could be more sure by investigating the network logs. I'd be curious to see if the traffic originated from the same host.

We can fix this in the short term by re-starting the instance. We would still be susceptible to the race condition, though. Are you able to deploy the application from `master` of the new repository?
