### ISSUE TITLE
compute_metrics.go is failing with "net/http: TLS handshake timeout"

### ISSUE THREAD

**Issue by rwaldron** [web-platform-tests/results-collection#486]
It's not _always_ the same file, but all one can always visit the timed out file directly

Examples: 

Run 1
```
2018/02/22 13:08:18 storage.go:320: Get https://storage.googleapis.com/wptd/b0ff0ea414/chrome-63.0-linux/2dcontext/shadows/2d.shadow.composite.1.html: net/http: TLS handshake timeout
```

Run 2
```
2018/02/22 13:40:36 storage.go:320: Get https://storage.googleapis.com/wptd/b0ff0ea414/safari-11.0-macos-10.12-sauce/2dcontext/drawing-images-to-the-canvas/2d.drawImage.negativesource.html: net/http: TLS handshake timeout
```

Run 3
```
2018/02/22 13:42:43 storage.go:320: Get https://storage.googleapis.com/wptd/9354b7ca60/edge-15-windows-10-sauce/2dcontext/pixel-manipulation/2d.imageData.put.modified.html: net/http: TLS handshake timeout
```

**Comment by rwaldron** [comment]
Update: when I apply [this patch](https://github.com/w3c/wptdashboard/commit/18b1235c4cfc82f816685be1d21a7527b74c78b1), the run will complete, but it logged 594 "net/http: TLS handshake timeout" errors. Another run, immediately following that produced only 56 "net/http: TLS handshake timeout" errors. 

I'm presently unable to determine the cause of this error? I tried to find the answer, but there seems to be a wide variety of potential causes.

**Comment by mdittmer** [comment]
@lukebjerring is this still the case?

**Comment by lukebjerring** [comment]
It is/might be, but we log, keep calm, and carry on on fetch errors now.
