### ISSUE TITLE
Split project into three separate repositories

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/results-collection#533]
We'd like to manage the code for the following projects using dedicated repositories:

- wpt.fyi (the web application that visualizes results)
- metrics (the code which analyses raw results data)
- runner (the infrastructure for collectiong results)

To do:

- [x] Label existing issues according to the project they describe
- [x] [Move code/documentation for wpt.fyi](https://github.com/web-platform-tests/wpt.fyi/issues/1)
- [x] [Move code/documentation for metrics calculation](https://github.com/web-platform-tests/results-analysis)
- [x] Move code/documentation for the runner

**Comment by jugglinmike** [comment]
Yeah, I was surprised, too. Though it's not quite complete:

https://github.com/w3c/wptdashboard/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+-label%3Aproject%3Arunner+-label%3Aproject%3Awpt.fyi+-label%3Aproject%3Ametrics

And here are the issues involving both "runner" and "wpt.fyi":

https://github.com/w3c/wptdashboard/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aproject%3Arunner+label%3Aproject%3Awpt.fyi

**Comment by jugglinmike** [comment]
Regarding the task labeled, "Move code/documentation for the runner," I created [a branch named `standalone-runner`](https://github.com/w3c/wptdashboard/tree/standalone-runner) as a short-term home for the runner project. Depending on how we decide to relocate the sub-projects, we can either initialize a new git repository from that branch or merge it into `master` here. In the mean time, I will be directing all my runner-related work towards that branch.

**Comment by foolip** [comment]
@mdittmer, what would you like the repo name for metrics to be?

**Comment by foolip** [comment]
I have a suggestion for the name of this repo itself, perhaps too tongue in cheek: run-wpt-run

**Comment by lukebjerring** [comment]
@mdittmer - I pushed a "probably works" subset of wpt.fyi to resolve https://github.com/web-platform-tests/wpt.fyi/issues/1

Moving metrics into a new repo will involve updating https://github.com/web-platform-tests/wpt.fyi package paths, so I recommend copying first, deleting second (as I did).

**Comment by foolip** [comment]
@jugglinmike, do you want the repo to be called "wpt-results-collector" or "wptresultscollector"? The two existing/planned repo names are wpt and wpt.fyi.

**Comment by foolip** [comment]
I've asked @plehegar to transfer this repo, will rename it after the move.

**Comment by foolip** [comment]
@jugglinmike, could you accept just "results-collector" with the prefix? @lukebjerring would like web-platform-tests/results-analysis for the metrics repo.

**Comment by jugglinmike** [comment]
Actually, I would prefer that name :)

...though while we're in the bikeshed: maybe we should align further. Either "results-collection" and "results-analysis" or "results-collector" and "results-analyzer".

**Comment by foolip** [comment]
@lukebjerring @mdittmer please pick :)

**Comment by mdittmer** [comment]
I say "collection" and "analysis". Doesn't assume there is One Collector/Analyzer to Rule Them All.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/results-analysis is created, @mdittmer is admin to hand out write permission.

When w3c/wptdashboard has been moved to web-platform-tests/results-collection I'll make @jugglinmike admin.

**Comment by jugglinmike** [comment]
Wait, what about "web-platform-tests/runner"?

**Comment by jugglinmike** [comment]
(kidding)

**Comment by foolip** [comment]
OK, https://github.com/web-platform-tests/results-collection now exists (this) repo and I've invited @jugglinmike to be the admin and did minor collaborator cleanup. @jugglinmike, please add or remove admins as you see fit.

**Comment by foolip** [comment]
This is now done. @jugglinmike, feel free to make the master branch of this repo the other temporary branch you had going. Perhaps some cleanup of branches in this repo is also warranted, but presumably not very urgent.

**Comment by jugglinmike** [comment]
@foolip I opened gh-538 for this very purpose. Would you mind merging it on my behalf?

**Comment by foolip** [comment]
@jugglinmike you're the repo admin, but I can rubberstamp it so it's green :)

**Comment by foolip** [comment]
Let's call it done, aftermath/follow-up can be filed as issues on the individual repos.
