### ISSUE TITLE
Update the README, point to other related repos

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-collection#539]
https://github.com/web-platform-tests/results-collection/blob/master/README.md needs to be updated. In particular, pointing to https://github.com/web-platform-tests/wpt.fyi would be helpful for those following old links, as I just did :)

**Comment by foolip** [comment]
https://github.com/web-platform-tests/results-analysis/blob/master/README.md is a nice example of this.

**Comment by jugglinmike** [comment]
Resolved via gh-540
