### ISSUE TITLE
display "should" test results differently

### ISSUE THREAD

**Issue by heycam** [web-platform-tests/results-collection#549]
There are some tests that are marked as tests of "should" conformance criteria, with `<meta name="flags" content="should">`.  Should the results of these tests be shown differently?  When I am scanning through test results and I see red table cells for test failures I would like to be able to see at a glance that it is not as dire as a regular test failure.

**Comment by jugglinmike** [comment]
This project is focused on collecting results data. Are the tests you're interested in visible on https://wpt.fyi ? If not, could you give some examples? That would help us diagnose the problem. If they are visible, then I suggest filing an issue against [the project for that website](https://github.com/web-platform-tests/wpt.fyi).

**Comment by lukebjerring** [comment]
Moved to https://github.com/web-platform-tests/wpt.fyi/issues/198
