### ISSUE TITLE
Collect results from the Edge browser at version 17

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/results-collection#559]
In https://github.com/web-platform-tests/wpt.fyi/issues/144, @lukebjerring wrote:

> Edge 17 now available, but 16 is shown on wpt.fyi.
> https://wiki.saucelabs.com/pages/viewpage.action?pageId=72009845

Update this project to collect results from Edge 17. Once reported, we expect the https://wpt.fyi website to reflect this new version without any change to its code base.

**Comment by jugglinmike** [comment]
I have merged https://github.com/web-platform-tests/results-collection/commit/7e99e57118b2dda50ddcc382487a43e4ea43d6c8, so the next scheduled collection should run against Edge version 17. I'll leave this issue open until the expected results are available on https://wpt.fyi.

**Comment by foolip** [comment]
Interesting, Edge 17 isn't available on BrowserStack yet, so it's not the case that Sauce *always* lags behind.

**Comment by jugglinmike** [comment]
Results from Edge 17 are now displayed on https://wpt.fyi:

![screenshot from 2018-05-16 20-00-26](https://user-images.githubusercontent.com/677252/40149833-fdfad4ba-5943-11e8-8428-96db74d0c70a.png)

**Comment by foolip** [comment]
Sweet, thank you @jugglinmike!
