### ISSUE TITLE
Collect results from the Safari browser at version 11.1

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/results-collection#562]
This project seeks to test the latest stable version of Apple Safari. At the time of this writing, the latest version is 11.1.

**Comment by jugglinmike** [comment]
We currently rely on the Sauce Labs service to collect results from Apple Safari, but this version is not yet available from that service. This will block our progress until it is resolved.

Sauce Labs publishes news regarding browser availability at the following URL:

https://wiki.saucelabs.com/pages/viewrecentblogposts.action?key=DOCS

**Comment by timsutton-sl** [comment]
It hasn't yet been published at the above URL, but support for Safari 11.1 on macOS 10.13 was just released on Sauce Labs today.

**Comment by jugglinmike** [comment]
Ooo, an insider tip! Thanks, Tim. We'll start on Monday!

**Comment by jugglinmike** [comment]
[We recently reconfigured the project to use the Safari 11.1](https://github.com/web-platform-tests/results-collection/commit/19aab09fe38e55c78d47e582e5599dd58de1076b), and tonight, the system uploaded [a full result set using that configuration](https://wpt.fyi/results/?sha=044cb1b9a7).

![screenshot from 2018-06-11 22-39-19](https://user-images.githubusercontent.com/677252/41267174-5c570f7c-6dc8-11e8-956c-3b063f656e6d.png)
