### ISSUE TITLE
Send browser_channel as a label to results receiver

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/results-collection#572]
From https://github.com/web-platform-tests/wpt.fyi/issues/245

```python
        response = requests.post(
            url,
            auth=(user_name, secret),
            data={'labels': browser_channel},
            files={'result_file': open(filename, 'rb')}
        )
```

Note: `labels` is a comma-separated string. Runners may add arbitrary labels and the wpt.fyi APIs can filter by labels.

cc @lukebjerring

**Comment by lukebjerring** [comment]
Shouldn't labels be an array of strings? That would make it more consistent with the golang struct and  json marshalling behavior.

**Comment by Hexcles** [comment]
@lukebjerring this is a HTML form not JSON, which doesn't really have arrays. It's more like the repeatable params we use in URLs.
