### ISSUE TITLE
calling os.remove() on the uploaded file causes error

### ISSUE THREAD

**Issue by thejohnjansen** [web-platform-tests/results-collection#583]
On Windows, whenever I hit line 104 to close the tmpfile(), I get an error that the file is in use.

**Comment by thejohnjansen** [comment]
I have a simple fix that I'll post now.

**Comment by thejohnjansen** [comment]
https://github.com/web-platform-tests/results-collection/pull/584

**Comment by jugglinmike** [comment]
Resolved via gh-584
