### ISSUE TITLE
Query "revision announcer" to select WPT revision

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/results-collection#591]
Currently, this project selects the revision of WPT to test according to the state of the HEAD reference of the git repository at the moment a collection attempt begins.

Recently, wpt.fyi was extended with a "revision announcer"--an HTTP endpoint which designates specific revisions of WPT for the purposes of coordination between multiple independent results collection systems.

Update this project to select the WPT revision by querying the revision announcer.

**Comment by foolip** [comment]
https://wpt.fyi/api/revisions/latest is the API.

**Comment by mdittmer** [comment]
If runners are locked to a certain cadence and need to "look back in time" to find the first not-yet-serviced commit, they can also use https://wpt.fyi/api/revisions/list

E.g.,

https://wpt.fyi/api/revisions/list?epochs=hourly&num_revisions=30

All epochs' metadata is at https://wpt.fyi/api/revisions/epochs
