### ISSUE TITLE
Collection from Sauce Labs-mediated browsers interrupted by extended delays

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/results-collection#598]
This project has failed to collect results from Edge and Safari since about 19:57 EDT on 2018-08-28.

The WPT CLI aborts testing if the time required to create a secure tunnel to Sauce Labs exceeds 30 seconds. As of yesterday, this window (which has been acceptable for many months) is no longer sufficient. https://status.saucelabs.com does not mention any service degradation, however. It's possible that this is an issue that has not yet been reported. It's also possible that this is the result of some trade-off made by the Sauce Labs technical leadership--that it is expected and therefore not considered a regression. I've filed a ticket with Sauce Labs technical support to see if they can provide any more detail.

We could avoid this by increasing the size of the window that the WPT CLI accepts. The window size is not currently configurable, so extending it will involve patching the WPT CLI (in addition to this project). The Sauce Labs support staff is generally very responsive (replying to many of my previous requests within one business day), so I would like to hold off on organizing those changes until we have a little more clarity on the underlying problem.

**Comment by foolip** [comment]
Thanks @jugglinmike! Waiting for a response from Sauce first would be good, up to 24h at least.

**Comment by gsnedders** [comment]
I'm all in favour of making it a parameter, given it really is pretty arbitrary, and could potentially also be affected by quality of connection and location.

**Comment by jugglinmike** [comment]
Great! [Here you go](https://github.com/web-platform-tests/wpt/pull/12783) :)

**Comment by jugglinmike** [comment]
The collections for Saturday (2018-09-01) and Sunday (2018-09-02) were both successful, so Sauce Labs may have resolved the underlying issue.

[The patch to the WPT CLI was merged today](https://github.com/web-platform-tests/wpt/pull/12783). The feature may make seem superfluous now, but we haven't received confirmation from Sauce Labs about the fix, so it's premature to expect stability. Additionally, there is always a possibility that this will regress in the future. In light of those two concerns, [I've incorporated the new argument into this project's process (increasing the timeout to 45 seconds)](https://github.com/web-platform-tests/results-collection/commit/3a7dbc4563c3e276e0c4f9e710f77f81adf78c26).

**Comment by jugglinmike** [comment]
The Sauce Labs staff updated the support ticket:

> The updates that caused this delay in launch times has been rolled back, so this should now be working as expected.

I'm sharing that here just to tie up the loose end. As noted above, while the delay has decreased to its normal duration, we're still using an extended timeout of 45 seconds to guard against future regressions.
