### ISSUE TITLE
Collect Safari stable results from Buildbot setup

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-collection#604]
https://github.com/web-platform-tests/results-collection/issues/112 has been resolved and we have reliable results from Safari Technology Preview.

The results for Safari stable are not as reliable, because they run over Sauce and have more timeouts.

Running on the same setup as Safari Technology Preview should resolve this.

**Comment by RByers** [comment]
This would be great, thanks!

**Comment by jugglinmike** [comment]
I started looking in to this today. As feared, it wasn't a simple matter of switching the name of the executable. Still, I'm optimistic that it won't take too much more effort.

**Comment by foolip** [comment]
We have the [first Safari 12 results](https://wpt.fyi/results/?sha=ee2e69bfb1&product=safari-12.0)! Interesting comparisons:
* [Safari 11 via Sauce vs. Safari 12 local](https://wpt.fyi/results/?sha=ee2e69bfb1&product=safari-11.1&product=safari-12.0&diff)
* [Safari 12 vs. Safari TP (both local)](https://wpt.fyi/results/?sha=ee2e69bfb1&product=safari-12.0&product=safari-12.1&diff)

**Comment by foolip** [comment]
I got so excited that I did a short writeup for webkit-dev:
https://lists.webkit.org/pipermail/webkit-dev/2018-October/030197.html

**Comment by jugglinmike** [comment]
We resolved this via gh-613 back in October. Closing!
