### ISSUE TITLE
Add a label of 'master' when uploading results to wpt.fyi

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/results-collection#622]
Required by https://github.com/web-platform-tests/wpt.fyi/issues/702

We're currently adding the branch-name as a label in TaskCluster:
https://github.com/web-platform-tests/wpt.fyi/blob/daa9a98a04313c9ff71d8f8cb031ed5f3d9f13d9/api/webhook/taskcluster.go#L332

(results: https://staging.wpt.fyi/test-runs?label=master )

**Comment by lukebjerring** [comment]
Fixed by https://github.com/web-platform-tests/results-collection/commit/b29c92ab444ccc62dc4ec668cf0e6a512dc4a4d0

**Comment by lukebjerring** [comment]
Thanks @jugglinmike !

**Comment by jugglinmike** [comment]
My pleasure :)
