### ISSUE TITLE
webdriver failing for Edge for some css reference tests

### ISSUE THREAD

**Issue by davidsgrogan** [web-platform-tests/results-collection#653]
I uploaded some tests a few days ago but Edge can't seem to run them. E.g.https://wpt.fyi/results/css/css-tables/subpixel-collapsed-borders-003.html?sha=8805f23ef6&label=master&product=chrome%5Bexperimental%5D&product=edge%5Bstable%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D

Expanding the Edge error reveals:

> ERROR message: Traceback (most recent call last):
  File "/home/raziel/worker/Remote_Chunked_Runner/build/tools/wptrunner/wptrunner/executors/base.py", line 162, in run_test
    result = self.do_test(test)
  File "/home/raziel/worker/Remote_Chunked_Runner/build/tools/wptrunner/wptrunner/executors/executorselenium.py", line 372, in do_test
    self.protocol.webdriver.set_window_rect(0, 0, 800 + width_offset, 600 + height_offset)
  File "/home/raziel/worker/Remote_Chunked_Runner/build/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1182, in set_window_rect
    "height": height})['value']
  File "/home/raziel/worker/Remote_Chunked_Runner/build/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/raziel/worker/Remote_Chunked_Runner/build/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: POST /session/XXXXXXXX-XXXX-XXXX-XXXX-XXXXe483ce1b/window/rect
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'sauce-win10', ip: '172.20.59.173', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown
Stacktrace:

**Comment by jugglinmike** [comment]
Thanks for the report! The good news is that the error is coming from the testing infrastructure, so it's unrelated to your patch.

Unlike many test-running bugs, this one seems reliable. The new tests have only been run 3 times, but the error interfered with all three attempts:

- https://wpt.fyi/results/css/css-tables/subpixel-collapsed-borders-003.html?sha=8805f23ef6&label=master&product=chrome%5Bexperimental%5D&product=edge%5Bstable%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D
- https://wpt.fyi/results/css/css-tables/subpixel-collapsed-borders-003.html?sha=70df598&label=master&product=chrome%5Bexperimental%5D&product=edge%5Bstable%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D
- https://wpt.fyi/results/css/css-tables/subpixel-collapsed-borders-003.html?sha=91b1eff&label=master&product=chrome%5Bexperimental%5D&product=edge%5Bstable%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D

Further, [the same error is reported for the generic test at infrastructure/reftest-wait.html](https://wpt.fyi/results/infrastructure/reftest-wait.html?sha=8805f23ef6).

It looks like things went sideways on February 7:

- [Passing status on February 5 - WPT commit 8f48bdf](https://wpt.fyi/results/infrastructure?sha=8f48bdf&label=master&product=chrome%5Bexperimental%5D&product=edge%5Bstable%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D)
- [Error status on February 7 - WPT commit 362afa3](https://wpt.fyi/results/infrastructure?sha=362afa3&label=master&product=chrome%5Bexperimental%5D&product=edge%5Bstable%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D)

<details>
  <summary><code>$ git log 362afa3...8f48bdf  --oneline</code></summary>

    362afa34cb Fix suppportedEntryTypes and PaintTiming IDLHarness tests
    5a6917c5cb Use oversampling to compute frame number
    ef3594e17b Move image loads out of the style struct accessors.
    9b2355cc88 XPath evaluate() fails if reusing an iterator result.
    9830c5ab11 [html] Restore utility method for query encoding
    de6f8fcf9b ReadableStream @@asyncIterator (#15097)
    d2c49d8610 XMLSerializer: Fix prefix generation algorithm
    71d0b286d5 Apply CSS clip inside the transform rather than outside.
    16057e18d4 Set a viewport meta tag explicitly to avoid window.scrollTo (or similar functions) works on mobile platforms.
    9fc797e6e5 Support the 'identity' XRReferenceSpace
    6374b9ac6b Add violation reporting to font-display feature policy
    77f3ead370 Fix repeat spacing for 'border-image's when combined with 'round'
    99b96dc056 Use print() function in both Python 2 and Python 3 (#15141)
    71a17e293b Try and improve #15159 by moving the window to a deterministic location
    5a406c55ff Add /tools/third_party to CODEOWNERS
    c70ddef532 Change CODEOWNERS to only cover the subtree in /css/tools
    edc48a7c12 Merge pull request #15248 from gsnedders/update-apiclient
    83364c672a Merge commit '77ff57a73af15f3ac3743a3eedf59d4acf6d0a41' into update-apiclient
    77ff57a73a Squashed 'css/tools/apiclient/' changes from 9d80ee4507..f0e1aa75a7
    fab38653d3 Added RTCErrorEvent and RTCErrorEventInit.
    0e9f46eaa8 Update mozlog from 3.10 to 4.0 (#15229)
    7a3ca09119 Update interfaces/mediasession.idl (#15246)
    73a0e277b9 WritableStream: test writer behaviour (#15235)
    fe78f2a1ad 12 new CSS Values tests and 3 reference files (#14986)
    1b287f0aac implemented 3 corrections detailed in issue 14160
    907716fdf2 [LayoutNG] Crash bug fix

</details>

Commit 71a17e293b (via [gh-15222](https://github.com/web-platform-tests/wpt/pull/15222)) is the most likely suspect. I'm going to keep digging.

**Comment by jugglinmike** [comment]
Tracing this error through our test running infrastructure (fun fact: when you split WPT into 100 segments, `infrastructure/reftest-wait.html` falls into number 18) and that of Sauce Labs (where every single test is tracked with a dedicated job), I found a slightly more helpful indication of the problem: the
"class" reported is an instance of `org.openqa.selenium.UnsupportedCommandException` (guess what language the Selenium server is written in).

Sure enough, [`window/rect` is not part of Selenium's wire protocol](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol). [I've filed a pull request to fix this in WPT](https://github.com/web-platform-tests/wpt/pull/15556); the results of your tests should be available from Edge once that's merged and we've collected from a subsequent revision.

**Comment by gsnedders** [comment]
@jugglinmike also a Selenium issue, given https://seleniumhq.github.io/selenium/docs/api/py/_modules/selenium/webdriver/remote/webdriver.html#WebDriver.set_window_rect definitely exists!

**Comment by gsnedders** [comment]
@jugglinmike also note that `window/rect` *does* exist in the W3C WebDriver protocol :/

**Comment by jugglinmike** [comment]
> also a Selenium issue

Agreed. I wrote a patch yesterday--just need to check if I can contribute under their CLA.

**Comment by jugglinmike** [comment]
The WPT patch landed, but not in time for today's results collection (we're currently collecting from [WPT revision 38bd28f](https://github.com/web-platform-tests/wpt/commits/38bd28f)). The fix will be observable in the results of tomorrow's collection, which ought to be available by Thursday. Assuming unrelated build errors don't interfere.

I'll leave this open until we can verify the results. Thanks for your patience!

**Comment by jugglinmike** [comment]
With the fix in place, Edge can now successfully run that test to completion:

https://wpt.fyi/results/css/css-tables/subpixel-collapsed-borders-003.html?sha=44e2efb923

@davidsgrogan The same goes for all the other new tests from [your patch](https://github.com/web-platform-tests/wpt/pull/15449). Do you think this is safe to close?

**Comment by davidsgrogan** [comment]
Yeah, this issue seems good, thanks. Though now Safari is having trouble running them, e.g. https://wpt.fyi/results/css/css-tables/subpixel-collapsed-borders-001.html?sha=44e2efb923 :/

**Comment by jugglinmike** [comment]
I just noticed this, too. I filed [a separate bug in WPT](https://github.com/web-platform-tests/wpt/issues/15625) because I don't think it's related to your tests or even to this repository.

**Comment by jugglinmike** [comment]
@gsnedders The CLA was approved, so here's that patch https://github.com/SeleniumHQ/selenium/pull/6994
