### ISSUE TITLE
Collection interrupted due to unexpected change in storage permissions

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/results-collection#655]
Some vendors do not provide a stable URL for browser binaries or WebDriver server binaries. The vendor-provided binaries may become unavailable while they are are in use by this project. To avoid this problem, this project persists binaries in an internally-managed object store.

At some time on 2019-03-15, the access control settings for the object store were modified to disallow anonymous public access. This project can not retrieve the cached binaries in this state, so all subsequent collection attempts for locally-installed browsers have failed. (Collections from Edge have *not* been effected because we do not cache any binaries for that browser.)

**Comment by jugglinmike** [comment]
I have resolved this by manually logging in to the Google Cloud Platform web interface and adding the "allUsers" Member to the "Storage Object Viewer" Role. Due to the current time requirements of collecting test results from Safari and Safari Technology Preview, we will not be able to recover the data that we have missed as a result of this interruption.

I'm curious about how this setting was changed, but unfortunately, the audit logging feature of our Google Cloud Platform account is currently disabled. My IAM user account lacks permission to enable this. @foolip: would you mind enabling audit logs for Google Cloud Storage (in case this problem recurs)?

**Comment by foolip** [comment]
@Hexcles you're more familiar with GCP and the different GCS buckets we have, can you help @jugglinmike take a look at what happened and enable audit logs?

**Comment by Hexcles** [comment]
Admin activity logs are enabled by default. You can see that in Logging > Logs > GCS Bucket (or other resources) -> cloudaudit.googleapis.com/activity .

And guess what? It was me who accidentally disabled the public read access of the "browser" bucket on March 15 when I was addressing a security concern of a totally different bucket raised by Google internal auditing. @jugglinmike I'm terribly sorry...

**Comment by jugglinmike** [comment]
Don't sweat it, Robert! We've had longer delays with far less sensible explanations (and others with no explanation at all). I'm just happy to know it wasn't our old friend the gce-enforcer.
