### ISSUE TITLE
SignedExchange tests failing in wpt.fyi

### ISSUE THREAD

**Issue by irori** [web-platform-tests/results-collection#663]
Currently, Signed Exchange tests are [not passing](https://wpt.fyi/results/signed-exchange?label=experimental&label=master&aligned) in wpt.fyi, because [pre-generated test certs / signed exchanges are expired](https://github.com/web-platform-tests/wpt/blob/master/signed-exchange/README.md).

To make them pass, we wave two options:

- Run Chrome with command-line flags that allows to ignore certificate / signature expiration errors, or
- Re-generate test certs and signed-exchanges before running the tests:
  - Signed Exchanges must be regenerated at least once per 7-days
  - Certificate must be regenerated at least once per 90-days
  - Generated certificate must be added as a trusted certificate in OS/browser

Which is more preferable?

**Comment by jugglinmike** [comment]
Hi there, @irori. This project is not currently being used to collect results for wpt.fyi. As of today, that task is performed by the Taskcluster service, and all the relevant system configuration is maintained within the web-platform-tests repository (largely in [the `tools/ci` directory](https://github.com/web-platform-tests/wpt/tree/master/tools/ci)). To make sure the right people see your request, I recommend [filing it within the web-platform-tests project itself](https://github.com/web-platform-tests/wpt/issues/new).

Sorry for the confusion. I'd like for the origin of the data to be more clear. I've suggested a feature for the wpt.fyi website that might have helped you; please make a comment there if you think that would help:

https://github.com/web-platform-tests/wpt.fyi/issues/378
