### ISSUE TITLE
Show historical test results on test file pages

### ISSUE THREAD

**Issue by jeffcarp** [web-platform-tests/results-collection#79]
A really useful thing we can show people is "when did this test start passing or failing?"

It'd be great if we could show something like this:

![historical-results-mock](https://user-images.githubusercontent.com/916028/29229667-818821a6-7e94-11e7-9e7e-41bcb3b0feba.png)

([drawing link](https://docs.google.com/drawings/d/1eJg95rfsk3HxSiLQpv1zPc6X54FriRPGZlD0UOpfjLY/edit?usp=sharing))

This can probably be done by a scheduled job that collects the last _n_ results for each platform and writes them to a summary JSON file, one for each test file.

**Comment by foolip** [comment]
Closing in favor of https://github.com/web-platform-tests/wpt.fyi/issues/22.
